######################################################################################
# SAB1 Critical File Permissions   #
######################################################################################

  - name: Review permisssions of critical files
    ansible.builtin.file:
      path: "{{ item.key }}"
      owner: root
      group: root
      mode: "{{ item.value }}"
      state: file
    with_dict:
      /etc/issue: '0644'
      /etc/issue.net: '0644'
      /etc/motd: '0644'
      /etc/passwd: '0644'
      /etc/passwd-: '0600'
      /etc/group: '0644'
      /etc/group-: '0644'
      /etc/ssh/sshd_config: '0600'
  
  - name: Debian specific permissions
    ansible.builtin.file:
      path: "{{ item.key }}"
      owner: root
      group: root
      mode: "{{ item.value }}"
    when: ansible_os_family == "Debian"
    with_dict: 
      /etc/shadow: '0640'
      /etc/gshadow: '0640'
      /etc/gshadow-: '0640'
      /etc/shadow-: '0640'

  - name: Redhat specific permissions
    ansible.builtin.file:
      path: "{{ item.key }}"
      owner: root
      group: root
      mode: "{{ item.value }}"
    when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky" 
    with_dict: 
      /etc/shadow: '0000'
      /etc/gshadow: '0000'
      /etc/gshadow-: '0000'
      /etc/shadow-: '0000'
