########################################################################################################
#  author: JA Vieitez
#  status: PROD
#
#   Install the latest docker engine to a Debian 12 host (x64)
########################################################################################################
---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Remove unofficial packages, if any
      apt:
        name: '{{ item }}'
        state: absent
        update_cache: false
      loop:
        - docker.io
        - docker-compose
        - docker-doc
        - podman-docker

    - name: Install basic dependencies
      apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      loop:
        - ca-certificates 
    
    - name: Make /etc/apt/keyrings dir
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download gpg key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: add sources.list entry
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable'
        state: present
        create: true

    - name: install Docker packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name: Add me to the docker group
      user:
        name: adges00
        groups: docker
        append: true

    - name: service up and enabled
      service:
        name: docker
        state: started
        enabled: true