---
- hosts: all
  become: False
#######################################################################################
# TO DO
# Add a check for required reboot. It's different in Debian and RHEL
#######################################################################################

  tasks:
#    - name: Check if reboot required (Debian)
#      stat:
#        path: /var/run/reboot-required
#      register: reboot_required
#      changed_when: reboot_required.stat.exists == True
#      when:  ansible_os_family == "Debian"

#    - name: Check if reboot required (Redhat)
#      command: "yum needs-restarting -r"
#      register: reboot_required
#      failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
#      changed_when: reboot_required.rc == 1
#      when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky" 
#      ignore_errors: yes

    - name: Show Inventory
      debug:
        msg: 
          - "Hostname: {{ inventory_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
          - "OS Family: {{  ansible_os_family }}"
          - "Domain: {{ ansible_domain }}"
          - "Memory: {{ ansible_memory_mb.real.total }} MB Total, {{ ansible_memory_mb.real.free }} free"
          - "Swap: {{ ansible_memory_mb.swap.total }} MB" 
          - "Uptime: {{ ansible_uptime_seconds }}"
          - "SELinux: {{ ansible_selinux.status }}"
          - "Service Manager: {{ ansible_service_mgr }}"
          - "Package Manager: {{ ansible_pkg_mgr }}"
          #- "Reboot Required: {{ reboot_required.changed | default('cannot tell') }}"





