---
- hosts: all
  become: yes
  tasks:

  - name: "Update apt cache"
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    when: ansible_pkg_mgr == "apt" 
    
     
  - name: "apt upgrade (Debian)"
    apt: force_apt_get=yes autoremove=yes upgrade=full cache_valid_time=3600
    register : apt_output
    when: ansible_pkg_mgr == "apt" 

  - name: Print Output
    debug: 
      msg: "{{ apt_output.stdout_lines | default('Nothing...') }}"
    when: ansible_pkg_mgr == "apt" 

  - name: dnf upgrade (RHEL)
    yum:
      name: '*'
      state: latest
    register : yum_output
    when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

  - name: Print Output
    debug: 
      msg: 
        - "{{ yum_output.msg | default('...') }}"
        - "{{ yum_output.results }}"
    when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
